# Portfolio Configuration File for Vinay Kumar Reddy Gadila - Java Full Stack Developer

site:
  name: "Vinay Kumar Reddy Gadila"
  title: "Java Full Stack Developer"
  tagline: "Experienced Full Stack Developer specializing in Java, AWS, Spring, Microservices, and Cloud Computing"
  description: "Portfolio of Vinay Kumar Reddy Gadila - A highly skilled Full Stack Java Developer with 7+ years of experience in software development, cloud technologies, and DevOps practices."
  url: "https://vinaykrgadila.com"  # Update with your actual portfolio URL
  logo: "/assets/images/logo.png" # Optional: Add logo image for your portfolio
  
theme:
  color_scheme: "dark"          # dark or light theme
  primary_color: "#007bff"     # Example primary color
  secondary_color: "#28a745"   # Example secondary color
  background_color: "#212529"  # Dark background color
  text_color: "#ffffff"        # White text for dark theme
  heading_color: "#ffffff"     # White headings
  link_color: "#007bff"        # Link color

navigation:
  menu:
    - name: "Home"
      url: "/"
    - name: "About Me"
      url: "/about"
    - name: "Skills"
      url: "/skills"
    - name: "Projects"
      url: "/projects"
    - name: "Blog"
      url: "/blog"
    - name: "Contact"
      url: "/contact"

footer:
  copyright: "2025 Vinay Kumar Reddy Gadila"
  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/vinaykrgadila"
    - name: "GitHub"
      url: "https://github.com/vinaykrgadila"
    - name: "Email"
      url: "mailto:vinaykrgadila@gmail.com"
    - name: "Twitter"
      url: "https://twitter.com/vinaykrgadila"
  social_icons:
    - "linkedin"
    - "github"
    - "twitter"

about:
  bio: |
    I am a passionate Java Full Stack Developer with 7+ years of experience in designing and developing software solutions for industries like retail, banking, healthcare, and government. 
    My expertise spans technologies such as Java, Spring, Angular, AWS, Python, and microservices, with a focus on building scalable and robust applications.
  education:
    - degree: "Master of Computer Science"
      school: "University of Dayton"
      year: "2023"
  experience:
    - title: "Full Stack Java Developer"
      company: "Caltrans, San Francisco, CA"
      duration: "Jan 2023 to Present"
      description: "Designed scalable cloud solutions using AWS services (EC2, S3, RDS), developed microservices using Spring Boot, Angular, and Python, integrated with AWS Lambda for serverless APIs."
    - title: "Full Stack Java Developer"
      company: "Great American Insurance, Cincinnati, OH"
      duration: "Jan 2021 to Dec 2022"
      description: "Worked on microservices with Spring Boot, Hibernate ORM, and integrated with cloud technologies like AWS for cloud deployments and CI/CD using Jenkins."
    - title: "Full Stack Java Developer"
      company: "Macys, Hyderabad, TG"
      duration: "July 2019 to Dec 2020"
      description: "Involved in front-end development with Angular and ReactJS, back-end development with Java, Hibernate, and Spring, and implemented cloud solutions using Azure."
    - title: "Full Stack Java Developer"
      company: "Chase, Hyderabad, TG"
      duration: "Feb 2018 to Jul 2019"
      description: "Worked with AWS, Java 8, and Spring Boot, built RESTful APIs, and integrated with Apache Kafka for messaging in microservices architecture."
      
skills:
  languages:
    - "Java (J2SE, J2EE 1.6/1.5/17)"
    - "SQL, PL/SQL"
    - "Python, Scala, Golang"
  technologies:
    - "Spring Boot, Spring MVC, Spring Cloud"
    - "Hibernate, JPA, JMS"
    - "AWS (EC2, S3, RDS, Lambda)"
    - "Docker, Kubernetes"
    - "Microservices, RESTful APIs"
    - "Angular, ReactJS, VueJS"
    - "Jenkins, Maven, Gradle"
    - "GraphQL, Kafka, RabbitMQ"
    - "Git, SVN, Bitbucket"
    - "Junit, Mockito, Selenium, Cypress"
  databases:
    - "Oracle, MySQL, PostgreSQL"
    - "MongoDB, Cassandra"
  frameworks:
    - "Spring Boot, Spring Security, Spring AOP"
    - "Hibernate ORM, Spring Batch"
    - "VueJS, Angular, ReactJS"
  tools:
    - "GitHub, GitLab, SVN"
    - "Docker, Kubernetes, Terraform"
    - "Jenkins, Maven, Gradle"
  methodologies:
    - "Agile, Scrum, Kanban"
    - "Test-Driven Development (TDD), Continuous Integration"

projects:
  - title: "Cloud-Based Traffic Management System"
    description: "Developed a scalable traffic management system using AWS Lambda, API Gateway, and Python for back-end processing."
    technologies: 
      - "AWS Lambda"
      - "API Gateway"
      - "Python"
      - "Spring Boot"
    link: "https://github.com/vinaykrgadila/traffic-management"
  - title: "E-commerce Platform"
    description: "Built an e-commerce platform with ReactJS and Spring Boot, integrating payment gateway and order management systems."
    technologies:
      - "ReactJS"
      - "Spring Boot"
      - "MySQL"
    link: "https://github.com/vinaykrgadila/ecommerce-platform"
  - title: "Microservices-Based Healthcare System"
    description: "Designed and implemented a microservices architecture for a healthcare system, allowing for seamless data flow and integrations."
    technologies:
      - "Spring Boot"
      - "Docker"
      - "MongoDB"
      - "Kubernetes"
    link: "https://github.com/vinaykrgadila/healthcare-system"

contact:
  email: "vinaykrgadila@gmail.com"
  phone: "(513) 916-4463"
  address: "San Francisco, CA, USA"
  form:
    enable_contact_form: true
    success_message: "Thank you for reaching out! I will get back to you soon."

analytics:
  google_analytics_id: "UA-XXXXX-Y"  # Replace with your actual Google Analytics tracking ID

# Performance optimizations
performance:
  optimize_images: true
  minify_js: true
  enable_lazy_loading: true
